POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2ODZkNDExMjQ3YWEwODc0NDc0YzdhZDciLCJpYXQiOjE3NTI0Mzg0MDh9._RHwvVA7h_Z0UITX-dCXd8eLrgFrVXlPgDcVi6jRR6A

{
  "title": "Token Auth in Practice",
  "author": "JWT Ninja",
  "url": "https://jwt.dev/token-auth",
  "likes": 10
}